* General Emacs Config
General config, this serves as a base to build upon using the modules in the module folder.
** User Interface, Theming & Aesthetics
*** Dashboard
Dashboard is a simple org file.
Extra functions defined to link to perspectives inside the org file.
#+BEGIN_SRC emacs-lisp
  (setq initial-buffer-choice ".emacs.d/dashboard.org")

  (defun dashboard-roam-perspective ()
    "Simple function to create and go to the Roam perspective."
    (persp-new "Roam")
    (persp-switch "Roam")
    (find-file "~/Sync/Notities/roam/20250411154025-index_roam.org"))

  (defun dashboard-development-perspective ()
    "Simple function to create and go to the Development perspective."
    (persp-new "Development")
    (persp-switch "Development")
    (find-file "~/Sync/Notities/roam/20250411153947-index_development.org"))

  (defun dashboard-latex-perspective ()
    "Simple function to create and go to the LaTeX perspective."
    (persp-new "LaTeX")
    (persp-switch "LaTeX")
    (find-file "/distrobox:LaTeX:~/Documenten/"))

  (defun dashboard-eshell-perspective ()
    "Simple function to create and go to the Development perspective."
    (persp-new "Eshell")
    (persp-switch "Eshell")
    (eshell))

#+END_SRC

*** Vertico
Minimal completion UI.
#+BEGIN_SRC emacs-lisp
  (use-package vertico
    :ensure t
    :bind (:map vertico-map
  	      ("C-j" . vertico-next)
  	      ("C-k" . vertico-previous)
  	      ("C-f" . vertico-exit)
  	      :map minibuffer-local-map
  	      ("M-h" . backward-kill-word))
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode))

  (use-package savehist
    :init
    (savehist-mode))

  (use-package marginalia
    :after vertico
    :ensure t
    :custom
    (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
    (marginalia-max-relative-
     (marginalia-align 'right)
     :init
     (marginalia-mode)))
    
#+END_SRC

Center the vertico frame in the middle of Emacs.
#+BEGIN_SRC emacs-lisp
  (use-package vertico-posframe
    :ensure t
    :init
    (vertico-posframe-mode))

  (setq vertico-posframe-parameters
      '((left-fringe . 24)
        (right-fringe . 24)))
#+END_SRC

#+RESULTS:
: ((left-fringe . 24) (right-fringe . 24))

*** Theme
**** Doom Themes & Modeline
Use Gruvbox as the theme for the editor.
#+BEGIN_SRC emacs-lisp
  (use-package doom-themes 
     :ensure t)
  (load-theme 'doom-gruvbox t)
#+END_SRC

Use doom-modeline as modeline.
#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))
#+END_SRC

**** Automatic Theme and Font
#+BEGIN_SRC emacs-lisp
  (use-package auto-dark
    :ensure t
    :custom
    (custom-safe-themes t)
    (auto-dark-themes '((doom-gruvbox) (doom-gruvbox-light)))

    :hook
    (auto-dark-dark-mode
     . (lambda ()
         ;; something to execute when dark mode is detected
         (vertico-posframe-cleanup)
         ))
    (auto-dark-light-mode
     . (lambda ()
         ;; something to execute when dark mode is detected
         (vertico-posframe-cleanup)
         ))
    :init (auto-dark-mode))
#+END_SRC

*** Hide Scrollbar, Menubar, Titlebar, Toolbar & Fullscreen
Hide UI elements to create a cleaner UI.
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark)) 
  (setq ns-use-proxy-icon nil)
  (setq default-frame-alist '((undecorated . t)))

  (add-to-list 'default-frame-alist
  	       '(vertical-scroll-bars . nil))

  (add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+END_SRC

*** All The Icons
Improve visuals by adding icons.
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons 
    :ensure t)
  
  (use-package all-the-icons-dired 
    :ensure t)

  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)

  (use-package all-the-icons-ibuffer
    :ensure t
    :hook (ibuffer-mode . all-the-icons-ibuffer-mode))
#+END_SRC

*** org-mode tweaks 
use the org-modern package to improve the visual look of org-mode.
#+BEGIN_SRC emacs-lisp
  (use-package org-modern
  	    :ensure t)
  (global-org-modern-mode)
  (global-visual-line-mode)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package org-superstar
    :ensure t)
  (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
#+END_SRC

*** Padding
Add some padding to all frames.
#+BEGIN_SRC emacs-lisp
  (use-package spacious-padding
	    :ensure t)
  (spacious-padding-mode t)
#+END_SRC

** Minor useful packages, Custom bindings & Tweaks
*** Which key
#+BEGIN_SRC emacs-lisp
  (use-package which-key 
     :ensure t)
  (which-key-mode)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package which-key-posframe
    :ensure t
    :config
    (which-key-posframe-mode))
#+END_SRC

*** Backup settings
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist
       `(("." . ,(concat user-emacs-directory "backups"))))
#+END_SRC

*** No littering
#+BEGIN_SRC emacs-lisp
  (use-package no-littering
     :ensure t)
#+END_SRC

*** Custom bindings
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c c") 'comment-or-uncomment-region)
  (global-set-key (kbd "C-c e") 'org-edit-src-code)
#+END_SRC

*** Undo Tree
#+BEGIN_SRC emacs-lisp
  (use-package undo-tree 
       :ensure t)
#+END_SRC

*** Restart Emacs
#+BEGIN_SRC emacs-lisp
  (use-package restart-emacs
    :ensure t)
#+END_SRC

*** Replace 'yes or no' with 'y or n'
#+BEGIN_SRC emacs-lisp
  (setq use-short-answers t)
#+END_SRC

*** Get rid of confirmation if file or buffer does not exist
#+BEGIN_SRC emacs-lisp
  (setq confirm-nonexistent-file-or-buffer nil)
#+END_SRC
*** Tramp modifications
#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'tramp
    ;; Find and modify the existing distrobox method
    (let ((method (assoc "distrobox" tramp-methods)))
      (if method
          ;; Modify the existing method
          (setcdr method
                  '((tramp-login-program "flatpak-spawn --host distrobox-enter")
                    (tramp-login-args (("enter") ("-n") ("%h")))
                    (tramp-remote-shell "/bin/sh")
                    (tramp-remote-shell-args ("-c"))))
        ;; Or add a new method if it doesn't exist
        (add-to-list 'tramp-methods
                     '("distrobox"
                       (tramp-login-program "flatpak-spawn --host distrobox-enter")
                       (tramp-login-args (("enter") ("-n") ("%h")))
                       (tramp-remote-shell "/bin/sh")
                       (tramp-remote-shell-args ("-c")))))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (defun latex-shell ()
      (interactive)
      (let ((default-directory "/distrobox:LaTeX:/home/daan/"))
        (shell)))
#+END_SRC

** Workflow
Add Vim keybinds.
#+BEGIN_SRC emacs-lisp
  (setq evil-want-keybinding nil)
  (use-package evil
	  :ensure t)
  (evil-mode 1)

  (use-package evil-tutor 
       :ensure t)

  (use-package evil-collection 
       :ensure t)

  (evil-collection-init)
#+END_SRC

Add the perspective package responsible for creating 'workspaces'.
#+BEGIN_SRC emacs-lisp
  (use-package perspective
    :ensure t  ;; use `:straight t` if using straight.el!
    :bind ("C-x k" . persp-kill-buffer*)
    :bind ("C-x p" . persp-switch)
    :custom (persp-mode-prefix-key (kbd "C-x m"))  ; pick your own prefix key here
    :init
    (persp-mode))

  ;; rename standard perspective from "main" to "Dashboard"
  (persp-rename "Dashboard")
#+END_SRC

* Sync Perspectives 
#+BEGIN_SRC emacs-lisp
  (require 'perspective)

  (defvar perspective-current-frame (selected-frame)
    "Current frame storing current state of perspectives.")

  (defvar perspective-shared-state nil
    "Shared global state of the perspectives.")

  (defun sync-perspectives-on-frame-switch ()
    "Responsible for syncing the perspectives between frames."
    (setq perspective-shared-state (frame-parameter perspective-current-frame 'persp--hash))
    (set-frame-parameter nil 'persp--hash (copy-hash-table perspective-shared-state))
    (setq perspective-current-frame (selected-frame)))

  (defun sync-perspectives-new-frame ()
    "Makes sure whenever a new frame is created it defaults to the Dashboard perspective."
    (persp-rename "Dashboard"))

  (add-hook 'focus-in-hook #'sync-perspectives-on-frame-switch)
  ;; (add-hook 'window-selection-change-functions #'sync-perspectives-new-frame)

  (add-hook 'window-selection-change-functions
    (lambda (frame)
      (sync-perspectives-new-frame)))
#+END_SRC
